// Blog


export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS'
export const GET_BLOG_LIST_FAIL = 'GET_BLOG_LIST_FAIL'
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS'
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL'


// Category

export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'


// Search

export const GET_BLOG_LIST_SEARCH_FAIL = 'GET_BLOG_LIST_SEARCH_FAIL'
export const GET_BLOG_LIST_SEARCH_SUCCESS = 'GET_BLOG_LIST_SEARCH_SUCCESS'